version: "3"

services:
  fastapi_app:
    build:
      context: .
      dockerfile: fastapi_app/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${FASTAPI_DATABASE_URL:-sqlite:///./test.db}

  flask_app:
    build:
      context: .
      dockerfile: flask_app/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env